Updated pro-no-market VPC and Subnet. Kibana dashboard imports disabled if no internet connection. Added customcert with given domain name.

diff --git a/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template b/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
--- a/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
+++ b/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
@@ -7,7 +7,7 @@ Parameters:
     Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance."
     Type: AWS::EC2::KeyPair::KeyName
     ConstraintDescription: "must be the name of an existing EC2 KeyPair."
-  
+
   KurentoAvailabilityZone:
     Type: AWS::EC2::AvailabilityZone::Name
     Description: must be the name of an existing AWS Availability Zone
@@ -17,7 +17,7 @@ Parameters:
     Type: String
     Description: Specifies the EC2 instance type for your OpenVidu instance
     Default: t2.large
-    AllowedValues: 
+    AllowedValues:
     - t2.large
     - t2.xlarge
     - t2.2xlarge
@@ -42,7 +42,7 @@ Parameters:
     Type: String
     Description: Specifies the EC2 instance type for your Kurento instances
     Default: t2.large
-    AllowedValues: 
+    AllowedValues:
     - t2.large
     - t2.xlarge
     - t2.2xlarge
@@ -63,15 +63,15 @@ Parameters:
     - c5.2xlarge
     ConstraintDescription: "Must be a valid EC2 instance type."
 
-  MyDomainName: 
+  MyDomainName:
     Description: "Valid DNS record name like mycompany.com."
     Type: String
     Default: openvidu.mycompany.com
     AllowedPattern: >-
       ^(?:_?(?>[a-z\d][a-z\d-]{0,61}[a-z\d]|[a-z\d])\.)*(?:_?(?>[a-z\d][a-z\d-]{0,61}[a-z\d]|[a-z\d]))\.?$
     ConstraintDescription: >-
-      Must be a valid DNS name. Like myapp.example.com 
-  
+      Must be a valid DNS name. Like myapp.example.com
+
   PublicElasticIP:
     Description: "Valid AWS elastic IP for using with Let's Encrypt or OwnCertificate."
     Type: String
@@ -80,12 +80,12 @@ Parameters:
       ^([01]?\d{1,2}|2[0-4]\d|25[0-5])\.([01]?\d{1,2}|2[0-4]\d|25[0-5])\.([01]?\d{1,2}|2[0-4]\d|25[0-5])\.([01]?\d{1,2}|2[0-4]\d|25[0-5])$
     ConstraintDescription: >-
       Must be a valid IP address. A valid IP address must be in the form of xxx.xxx.xxx.xxx, where xxx is a number from 0-255.
-  
+
   OpenViduSecret:
     Description: "Secret to connect to your OpenVidu Server and Kibana Dashboard."
     Type: String
     NoEcho: true
-  
+
   OpenviduCDREnable:
     Description: "Whether to enable Call Detail Record or not"
     Type: String
@@ -105,8 +105,8 @@ Parameters:
     Description: "Password for Kibana Dashboard"
     Type: String
     NoEcho: true
-  
-  WhichCert: 
+
+  WhichCert:
     Description: "You can choose from the list below which certificate to use."
     Type: String
     Default: selfsigned
@@ -114,16 +114,16 @@ Parameters:
     - selfsigned
     - letsencrypt
     - owncert
-  
+
   LetsEncryptEmail:
     Description: "Email necesary for Let's Encrypt notifications."
     Type: String
-  
+
   OwnCertCRT:
     Description: "URL to the CRT file"
     Type: String
 
-  OwnCertKEY: 
+  OwnCertKEY:
     Description: "URL to the KEY file"
     Type: String
 
@@ -134,32 +134,32 @@ Parameters:
     AllowedValues:
     - true
     - false
-  
+
   OpenviduRecordingNotification:
     Description: "Which users should receive the recording events in the client side (recordingStarted, recordingStopped)."
     Type: String
     Default: "publisher_moderator"
-    AllowedValues: 
+    AllowedValues:
     - "all"
     - "publisher_moderator"
     - "moderator"
     - "none"
-  
-  OpenviduStreamsVideoMaxRecvBandwidth: 
+
+  OpenviduStreamsVideoMaxRecvBandwidth:
     Description: "Maximum video bandwidth sent from clients to OpenVidu Server, in kbps. 0 means unconstrained."
     Type: Number
     Default: 0
-    
+
   OpenviduStreamsVideoMinRecvBandwidth:
     Description: "Minimum video bandwidth sent from clients to OpenVidu Server, in kbps. 0 means unconstrained."
     Type: Number
     Default: 0
 
-  OpenviduStreamsVideoMaxSendBandwidth: 
+  OpenviduStreamsVideoMaxSendBandwidth:
     Description: "Maximum video bandwidth sent from OpenVidu Server to clients, in kbps. 0 means unconstrained."
     Type: Number
     Default: 0
-    
+
   OpenviduStreamsVideoMinSendBandwidth:
     Description: "Minimum video bandwidth sent from OpenVidu Server to clients, in kbps. 0 means unconstrained."
     Type: Number
@@ -189,27 +189,17 @@ Parameters:
     Type: String
     Default: "sessionCreated,sessionDestroyed,participantJoined,participantLeft,webrtcConnectionCreated,webrtcConnectionDestroyed,recordingStatusChanged"
 
-  OpenViduCidrBlock:
+  OpenViduVPC:
     Description: "Dedicated VPC for OpenVidu cluster"
-    Type: String
-    Default: 172.16.0.0/16
-    AllowedPattern: >-
-      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
-    ConstraintDescription: >-
-      Must be in CIDR notation
+    Type: AWS::EC2::VPC::Id
 
   OpenViduSubnet:
     Description: "Subnet for OpenVidu cluster"
-    Type: String
-    Default: 172.16.0.0/24
-    AllowedPattern: >-
-      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
-    ConstraintDescription: >-
-      Must be in CIDR notation
+    Type: AWS::EC2::Subnet::Id
 
   OpenviduClusterLoadStrategy:
     Description: >
-      What parameter should be used to distribute the creation of new sessions 
+      What parameter should be used to distribute the creation of new sessions
       (and therefore distribution of load) among all available KMSs. Can be: [streams, sessions, mediaObjects, cpu]
     Type: String
     Default: streams
@@ -269,7 +259,7 @@ Metadata:
         Label:
           default: Networking Info
         Parameters:
-        - OpenViduCidrBlock
+        - OpenViduVPC
         - OpenViduSubnet
         - KurentoAvailabilityZone
 
@@ -282,12 +272,12 @@ Metadata:
         default: "Instance Type For Openvidu Server"
       AwsInstanceTypeKMS:
         default: "Instance Type For Kurento Media Server"
-      MyDomainName: 
+      MyDomainName:
         default: "FQDN"
       PublicElasticIP:
         default: "Public Elastic IP"
       OpenViduSecret:
-        default: "OpenVidu Secret" 
+        default: "OpenVidu Secret"
       OpenviduCDREnable:
         default: "OpenVidu Server Call Detail Record"
       MediaNodesStartNumber:
@@ -302,17 +292,17 @@ Metadata:
         default: "Let's Encrypt Email"
       OwnCertCRT:
         default: "CRT File"
-      OwnCertKEY: 
+      OwnCertKEY:
         default: "KEY File"
       FreeHTTPAccesToRecordingVideos:
         default: "Video Recording Access"
       OpenviduRecordingNotification:
         default: "Recording Notifications"
-      OpenviduStreamsVideoMaxRecvBandwidth: 
+      OpenviduStreamsVideoMaxRecvBandwidth:
         default: "Openvidu Streams Video Max Recv Bandwidth"
       OpenviduStreamsVideoMinRecvBandwidth:
         default: "Openvidu Streams Video Min Recv Bandwidth"
-      OpenviduStreamsVideoMaxSendBandwidth: 
+      OpenviduStreamsVideoMaxSendBandwidth:
         default: "Openvidu Streams Video Max Send Bandwidth"
       OpenviduStreamsVideoMinSendBandwidth:
         default: "Openvidu Streams Video Min Send Bandwidth"
@@ -331,7 +321,7 @@ Metadata:
       OpenviduClusterLoadStrategy:
         default: "Openvidu Cluster Load Strategy"
 
-Conditions: 
+Conditions:
   NoSelfSigned:
     'Fn::Not':
       - 'Fn::Equals':
@@ -339,52 +329,6 @@ Conditions:
           - selfsigned
 
 Resources:
-
-  OpenViduVPC:
-    Type: 'AWS::EC2::VPC'
-    Properties:
-      CidrBlock: !Ref OpenViduCidrBlock
-      EnableDnsSupport: true
-      EnableDnsHostnames: true
-      Tags:
-        - Key: Name
-          Value: OpenViduVPC
-
-  OpenViduSubnet1:
-    Type: 'AWS::EC2::Subnet'
-    Properties:
-      CidrBlock: !Ref OpenViduSubnet
-      VpcId: !Ref OpenViduVPC
-      AvailabilityZone: !Ref KurentoAvailabilityZone
-      MapPublicIpOnLaunch: true
-
-  InternetGateway:
-    Type: 'AWS::EC2::InternetGateway'
-
-  AttachInternetGateway:
-    Type: 'AWS::EC2::VPCGatewayAttachment'
-    Properties:
-      VpcId: !Ref OpenViduVPC
-      InternetGatewayId: !Ref InternetGateway
-
-  RouteTable:
-    Type: AWS::EC2::RouteTable
-    Properties:
-      VpcId: !Ref OpenViduVPC
-
-  PublicSubnet1RouteTableAssociation:
-    Type: 'AWS::EC2::SubnetRouteTableAssociation'
-    Properties:
-      RouteTableId: !Ref RouteTable
-      SubnetId: !Ref OpenViduSubnet1
-
-  InternetRoute:
-    Type: AWS::EC2::Route
-    DependsOn: AttachInternetGateway
-    Properties: 
-      RouteTableId: !Ref RouteTable
-      DestinationCidrBlock: 0.0.0.0/0
-      GatewayId: !Ref InternetGateway
 
   OpenViduManageEC2Role:
     Type: 'AWS::IAM::Role'
@@ -423,7 +367,7 @@ Resources:
       Roles:
         - !Join [ "-", [ OpenViduManageEC2Role, !Ref 'AWS::Region'] ]
     DependsOn:
-      - OpenViduManageEC2Role  
+      - OpenViduManageEC2Role
 
   OpenViduServer:
     Type: AWS::EC2::Instance
@@ -435,9 +379,9 @@ Resources:
             "/usr/local/bin/feedGroupVars.sh":
               content: !Sub |
                 #!/bin/bash -xe
-                
+
                 cd /usr/src/openvidu
-                
+
                 PIP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
                 PublicHostname=$(curl http://169.254.169.254/latest/meta-data/public-hostname)
                 AWS_AMI_ID=KMS_AMI_ID
@@ -496,6 +440,19 @@ Resources:
               mode: "000755"
               owner: "root"
               group: "root"
+            "/usr/local/bin/checkInternetConnection.sh":
+              content: !Sub |
+                #!/bin/bash
+
+                # Check Internet connection
+                ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null \
+                  && internet_connection=true || internet_connection=false
+
+                # If there is no internet connection, Kibana will not be started
+                sed -i "s/NO_INTERNET/$internet_connection/" group_vars/all
+              mode: "000755"
+              owner: "root"
+              group: "root"
     Properties:
       ImageId: !FindInMap [OVAMIMAP, !Ref 'AWS::Region', AMI]
       InstanceType: !Ref AwsInstanceTypeOV
@@ -510,7 +467,7 @@ Resources:
         - Key: 'ov-cluster-member'
           Value: 'server'
       UserData:
-        "Fn::Base64": 
+        "Fn::Base64":
           !Sub |
             #!/bin/bash -xe
 
@@ -521,6 +478,8 @@ Resources:
             if [ "${WhichCert}" == "owncert" ]; then
               /usr/local/bin/buildCerts.sh || { echo "[Openvidu] error with the certificate files"; exit 1; }
             fi
+
+            /usr/local/bin/checkInternetConnection.sh || { echo "[Openvidu] error checking internet connection"; exit 1; }
 
             cd /usr/src/openvidu
 
@@ -544,7 +503,7 @@ Resources:
 
             # sending the finish call
             /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WaitCondition --region ${AWS::Region}
-            
+
       BlockDeviceMappings:
         - DeviceName: /dev/sda1
           Ebs:
@@ -552,7 +511,7 @@ Resources:
             Iops: 200
             DeleteOnTermination: true
             VolumeSize: 50
-      
+
   KMSSecurityGroup:
     Type: 'AWS::EC2::SecurityGroup'
     Properties:
@@ -593,7 +552,7 @@ Resources:
     Type: 'AWS::EC2::SecurityGroup'
     Properties:
       GroupDescription: SSH, Proxy and OpenVidu WebRTC Ports
-      VpcId: !Ref OpenViduVPC      
+      VpcId: !Ref OpenViduVPC
       SecurityGroupIngress:
         - IpProtocol: udp
           FromPort: 40000
@@ -636,7 +595,7 @@ Resources:
           FromPort: 1
           ToPort: 65535
           CidrIp: 0.0.0.0/0
-  
+
   WaitCondition:
     Type: AWS::CloudFormation::WaitCondition
     CreationPolicy:
@@ -654,10 +613,10 @@ Resources:
 Outputs:
   OpenViduInspector:
     Description: "Use this URL to connect OpenVidu with user and password"
-    Value: !Join 
+    Value: !Join
         - ''
         - - 'https://'
-          - !GetAtt OpenViduServer.PublicDnsName 
+          - !GetAtt OpenViduServer.PublicDnsName
           - '/inspector'
 
   OpenViduInspectorLE:
@@ -668,7 +627,7 @@ Outputs:
           - !Ref MyDomainName
           - '/inspector'
     Condition: NoSelfSigned
-  
+
   Kibana:
     Description: "Check out graph and performance of your OpenVidu installation"
     Value: !Join
