ov CF and kms CF changed

diff --git a/aws_marketplace/cfn-mkt-kms-ami.yaml.template b/aws_marketplace/cfn-mkt-kms-ami.yaml.template
--- a/aws_marketplace/cfn-mkt-kms-ami.yaml.template
+++ b/aws_marketplace/cfn-mkt-kms-ami.yaml.template
@@ -66,32 +66,35 @@ Resources:
               mode: "000755"
               owner: "root"
               group: "root"
-            "/usr/local/bin/runKMS.sh":
+            "/usr/local/bin/installMediaNode.sh":
               content: |
                 #!/bin/bash
                 set -eu -o pipefail
+                
+                # Install kms
+                cd /opt
+                curl https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_media_node_OPENVIDU_VERSION.sh | bash
+                
                 # Create recording folder
                 mkdir -p /opt/openvidu/recordings
                 chmod 777 /opt/openvidu/recordings
+                
                 # Configure crash report
                 mkdir -p /opt/openvidu/kms-crashes
                 sed -i "s/enabled=1/enabled=0/" /etc/default/apport
                 echo "kernel.core_pattern=/opt/openvidu/kms-crashes/core_%e_%p_%u_%t" >> /etc/sysctl.conf
                 sysctl --system
-                # Run KMS
-                cd /opt/kms
-                docker-compose up -d
               mode: "000755"
               owner: "root"
               group: "root"
-            "/usr/local/bin/getDockerCompose.sh":
+            "/usr/local/bin/runMediaNode.sh":
               content: |
                 #!/bin/bash
                 set -eu -o pipefail
-                # Installation path
-                cd /opt
-                # Install kms
-                curl https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_media_node_OPENVIDU_VERSION.sh | bash
+
+                # Run KMS
+                cd /opt/kms
+                docker-compose up -d
               mode: "000755"
               owner: "root"
               group: "root"
@@ -115,9 +118,9 @@ Resources:
 
             /usr/local/bin/installDockerAndDockerCompose.sh || { echo "[Openvidu] error installing software"; exit 1; }
 
-            /usr/local/bin/getDockerCompose.sh || { echo "[Openvidu] error getting Docker compose"; exit 1; }
+            /usr/local/bin/installMediaNode.sh || { echo "[Openvidu] error installing Media Node"; exit 1; }
 
-            /usr/local/bin/runKMS.sh || { echo "[Openvidu] error installing Kurento Media Server"; exit 1; }
+            /usr/local/bin/runMediaNode.sh || { echo "[Openvidu] error running Media Node"; exit 1; }
 
             # sending the finish call
             /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WaitCondition --region ${AWS::Region}
