Add security groups in userData

diff --git a/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template b/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
--- a/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
+++ b/aws_marketplace/cfn-openvidu-server-pro-no-market.yaml.template
@@ -307,6 +307,7 @@ Resources:
                   - 'ec2:TerminateInstances'
                   - 'ec2:CreateTags'
                   - 'ec2:DescribeSecurityGroups'
+                  - 'ec2:AuthorizeSecurityGroupIngress'
                   - 'iam:PassRole'
                   - 'route53:ChangeResourceRecordSets'
                   - 'route53:ListHostedZones'
@@ -394,14 +395,9 @@ Resources:
                 sed -i "s/#AWS_STACK_ID=/AWS_STACK_ID=$(echo ${AWS::StackId} | sed 's#/#\\/#g')/" $WORKINGDIR/.env
                 sed -i "s/#AWS_STACK_NAME=/AWS_STACK_NAME=${AWS::StackName}/" $WORKINGDIR/.env
 
-                SECGRPID=$(docker run --rm amazon/aws-cli:2.0.7 ec2 describe-security-groups \
-                               --region ${AWS::Region} \
-                               --output text \
-                               --filters "Name=tag:aws:cloudformation:logical-id,Values=KMSSecurityGroup" \
-                                         "Name=tag:aws:cloudformation:stack-id,Values=${AWS::StackId}" \
-                               --query 'SecurityGroups[].GroupId[]'
-                )
-                sed -i "s/#AWS_SECURITY_GROUP=/AWS_SECURITY_GROUP=$SECGRPID/" $WORKINGDIR/.env
+                # Get security group id of kms and use it as env variable
+                SECGRPIDKMS=$(/usr/local/bin/getSecurityGroupKms.sh)
+                sed -i "s/#AWS_SECURITY_GROUP=/AWS_SECURITY_GROUP=$SECGRPIDKMS/" $WORKINGDIR/.env
 
                 # Without Application
                 if [ "${WantToDeployDemos}" == "false" ]; then
@@ -418,6 +414,59 @@ Resources:
                 WORKINGDIR=/opt/openvidu
                 wget --no-check-certificate -O $WORKINGDIR/owncert/certificate.cert ${OwnCertCRT}
                 wget --no-check-certificate -O $WORKINGDIR/owncert/certificate.key ${OwnCertKEY}
+              mode: "000755"
+              owner: "root"
+              group: "root"
+              '/usr/local/bin/getSecurityGroupKms.sh':
+              content: !Sub |
+                #!/bin/bash -x
+                docker run --rm amazon/aws-cli:2.0.7 ec2 describe-security-groups \
+                               --region ${AWS::Region} \
+                               --output text \
+                               --filters "Name=tag:aws:cloudformation:logical-id,Values=KMSSecurityGroup" \
+                                         "Name=tag:aws:cloudformation:stack-id,Values=${AWS::StackId}" \
+                               --query 'SecurityGroups[].GroupId[]'
+              mode: "000755"
+              owner: "root"
+              group: "root"
+            '/usr/local/bin/getSecurityGroupOpenVidu.sh':
+              content: !Sub |
+                #!/bin/bash -x
+                docker run --rm amazon/aws-cli:2.0.7 ec2 describe-security-groups \
+                               --region ${AWS::Region} \
+                               --output text \
+                               --filters "Name=tag:aws:cloudformation:logical-id,Values=OpenViduSecurityGroup" \
+                                         "Name=tag:aws:cloudformation:stack-id,Values=${AWS::StackId}" \
+                               --query 'SecurityGroups[].GroupId[]'
+              mode: "000755"
+              owner: "root"
+              group: "root"
+            '/usr/local/bin/getCidrBlocKSubnet.sh':
+              content: !Sub |
+                #!/bin/bash -x
+                docker run --rm amazon/aws-cli:2.0.7 ec2 describe-subnets \
+                                --region ${AWS::Region} \
+                                --output text \
+                                --filters "Name=subnet-id,Values=${OpenViduSubnet}" \
+                                --query 'Subnets[].CidrBlock[]'
+              mode: "000755"
+              owner: "root"
+              group: "root"
+            '/usr/local/bin/create_security_group_rules.sh':
+              content: !Sub |
+                #!/bin/bash -x
+                SECGRPIDKMS=$(/usr/local/bin/getSecurityGroupKms.sh)
+                SECGRPIDOV=$(/usr/local/bin/getSecurityGroupOpenVidu.sh)
+                SUBNET_CIDR=$(/usr/local/bin/getCidrBlocKSubnet.sh)
+
+                # Create Security group rules OpenVidu
+                docker run --rm amazon/aws-cli:2.0.7 ec2 authorize-security-group-ingress --group-id $SECGRPIDOV --protocol tcp --port 5044 --cidr $SUBNET_CIDR
+                docker run --rm amazon/aws-cli:2.0.7 ec2 authorize-security-group-ingress --group-id $SECGRPIDOV --protocol tcp --port 9200 --cidr $SUBNET_CIDR
+
+                # Create security group rules for KMS
+                docker run --rm amazon/aws-cli:2.0.7 ec2 authorize-security-group-ingress --group-id $SECGRPIDKMS --protocol tcp --port 8888 --cidr $SUBNET_CIDR
+                docker run --rm amazon/aws-cli:2.0.7 ec2 authorize-security-group-ingress --group-id $SECGRPIDKMS --protocol tcp --port 3000 --cidr $SUBNET_CIDR
+
               mode: "000755"
               owner: "root"
               group: "root"
@@ -462,6 +511,9 @@ Resources:
             # Replace .env variables
             /usr/local/bin/feedGroupVars.sh || { echo "[Openvidu] Parameters incorrect/insufficient"; exit 1; }
 
+            # Create security groups
+            /usr/local/bin/create_security_group_rules.sh || { echo "[Openvidu] Error creating security groups"; exit 1; }
+
             # Launch on reboot
             echo "@reboot /usr/local/bin/restartPRO.sh" | crontab
 
@@ -500,14 +552,6 @@ Resources:
           FromPort: 22
           ToPort: 22
           CidrIp: 0.0.0.0/0
-        - IpProtocol: tcp
-          FromPort: 8888
-          ToPort: 8888
-          SourceSecurityGroupName: !Join [ "-", [ !Ref 'AWS::StackName', 'OpenViduSecurityGroup'] ]
-        - IpProtocol: tcp
-          FromPort: 3000
-          ToPort: 3000
-          SourceSecurityGroupName: !Join [ "-", [ !Ref 'AWS::StackName', 'OpenViduSecurityGroup'] ]
         - IpProtocol: udp
           FromPort: 40000
           ToPort: 65535
@@ -553,14 +597,6 @@ Resources:
           FromPort: 3478
           ToPort: 3478
           CidrIp: 0.0.0.0/0
-        - IpProtocol: tcp
-          FromPort: 5044
-          ToPort: 5044
-          SourceSecurityGroupName: !Join [ "-", [ !Ref 'AWS::StackName', 'KMSSecurityGroup'] ]
-        - IpProtocol: tcp
-          FromPort: 9200
-          ToPort: 9200
-          SourceSecurityGroupName: !Join [ "-", [ !Ref 'AWS::StackName', 'KMSSecurityGroup'] ]
         - IpProtocol: udp
           FromPort: 40000
           ToPort: 65535
