error handling

diff --git a/roles/openvidu/templates/launch_kms.sh.j2 b/roles/openvidu/templates/launch_kms.sh.j2
--- a/roles/openvidu/templates/launch_kms.sh.j2
+++ b/roles/openvidu/templates/launch_kms.sh.j2
@@ -12,6 +12,33 @@ export AWS_DEFAULT_REGION={{ aws_default_region }}
 
 TMPFILE=$(mktemp -t openvidu-userdata-XXX --suffix .txt)
 OUTPUT=$(mktemp -t openvidu-launch-kms-XXX --suffix .json)
+ERROUTPUT=$(mktemp -t openvidu-launch-kms-XXX --suffix .err)
+
+trap exit_on_error ERR
+
+exit_on_error () {
+  ERROR_TYPE=$(cat ${ERROUTPUT} | awk '{ print $4 }' | sed -r 's/\(|\)//g' | tr -d '\n')
+
+  case ${ERROR_TYPE}
+  in
+    "InvalidParameterValue")
+      echo -e "Parameter invalid " $(cat ${ERROUTPUT}) >&2
+      exit 1
+      ;;
+
+    "UnauthorizedOperation")
+      MSG_COD=$(cat ${ERROUTPUT} | awk -F: '{ print $3 }')
+      MSG_DEC=$(aws sts decode-authorization-message --encoded-message ${MSG_COD})
+
+      echo -e "Unauthorized " $(cat ${MSG_DEC}) >&2
+      exit 1
+      ;;
+    *)
+      echo -e "Unknown error " $(cat ${ERROUTPUT}) >&2
+      exit 1
+      ;;
+  esac
+}
 
 cat >${TMPFILE}<<FDF
 #!/bin/bash -xe
@@ -50,12 +77,17 @@ aws ec2 run-instances \
     --tag-specifications 'ResourceType=instance,Tags=[{Key="Name",Value="Kurento Media Server"},{Key="ov-cluster-member",Value="kms"}]' \
     --user-data file://${TMPFILE} \
     --iam-instance-profile Name=OpenViduInstanceProfile \
-    --security-group-ids ${SECURITY_GROUP} > ${OUTPUT}
+    --security-group-ids ${SECURITY_GROUP} > ${OUTPUT} 2> ${ERROUTPUT}
 
 KMS_IP=$(cat ${OUTPUT} | jq --raw-output ' .Instances[] | .NetworkInterfaces[0] | .PrivateIpAddress')
 KMS_ID=$(cat ${OUTPUT} | jq --raw-output ' .Instances[] | .InstanceId')
 
-echo ${KMS_ID} ${KMS_IP} >> /opt/openvidu/kms_list.txt
+JSON_OUTPUT=$(jq -n \
+  --arg id "${KMS_ID}" \
+  --arg ip "${KMS_IP}" \
+  '{ id: $id, ip: $ip }')
+
+echo ${JSON_OUTPUT} > /opt/openvidu/instances/kms_list.json
 
 rm ${TMPFILE}
 rm ${OUTPUT}
